import utilidades as ut
import generador_de_problemas as gp
def main():
    ut.clear()
    ut.formato("Bienvenido a tu examen PISA, a continuacion se te presentaran 2 problemas por tema","WHITE","BLACK",True)
    ut.pausa()
    ut.clear()
    ut.formato("Entraras a la seccion de aritmetica",color="RED",animacion=True)
    ut.registrar_calificacion("Examen",gp.aritmetica())
    ut.registrar_calificacion("Examen",gp.aritmetica())
    ut.pausa()
    ut.clear()
    ut.formato("Entraras a la seccion de algebra",color="RED",animacion=True)
    ut.registrar_calificacion("Examen",gp.algebra())
    ut.registrar_calificacion("Examen",gp.algebra())
    ut.pausa()
    ut.clear()
    ut.formato("Entraras a la seccion de geometria", color="RED", animacion=True)
    ut.registrar_calificacion("Examen",gp.geometria())
    ut.registrar_calificacion("Examen",gp.geometria())
    ut.pausa()
    ut.clear()
    ut.formato("Entraras a la seccion de funciones y graficas",color="RED",animacion=True)
    ut.registrar_calificacion("Examen",gp.funciones_y_graficas())
    ut.registrar_calificacion("Examen",gp.funciones_y_graficas())
    ut.pausa()
    ut.clear()
    ut.formato("Entraras a la seccion de estadistica descriptiva",color="RED",animacion=True)
    ut.registrar_calificacion("Examen",gp.estadistica_descriptiva())
    ut.registrar_calificacion("Examen",gp.estadistica_descriptiva())
    ut.pausa()
    ut.clear()
    ut.formato("Combinatoria y Probabilidad",color="RED",animacion=True)
    ut.registrar_calificacion("Examen",gp.combinatoria_probabilidad())
    ut.registrar_calificacion("Examen",gp.combinatoria_probabilidad())
    ut.pausa()
    ut.clear()